/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Edy
 */
public class Completar extends javax.swing.JFrame {
    //Variables
    Validaciones val = new Validaciones();//Construccion del la clase que tiene las validaciones
    ArrayList<Usuario> usuarios;//Arreglo de usuario
    int idUsuario;//Usuario logueado
    /**
     * Creates new form Completar
     */
    
    public Completar() {
        initComponents();
    }
    
    //Para llamar al form y automaticamente agregarle la lista de usuarios y el usuario logeado
    public Completar(ArrayList<Usuario> usuarios, int idUsuario) {
        initComponents();
        this.usuarios = usuarios;
        this.idUsuario = idUsuario;
        lbUsuario.setText(usuarios.get(idUsuario).cuenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tboxNombre = new javax.swing.JTextField();
        tbxEdad = new javax.swing.JTextField();
        lbRegistro = new javax.swing.JLabel();
        btnCompletar = new javax.swing.JButton();
        lbLogged = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tboxNombre.setText("Ingrese su nombre completo");
        tboxNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tboxNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tboxNombreFocusLost(evt);
            }
        });
        tboxNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tboxNombreKeyTyped(evt);
            }
        });

        tbxEdad.setText("Ingrese su edad");
        tbxEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbxEdadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbxEdadFocusLost(evt);
            }
        });
        tbxEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbxEdadKeyTyped(evt);
            }
        });

        lbRegistro.setText("Es su primer login complete los siguientes datos:");

        btnCompletar.setText("Completar");
        btnCompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletarActionPerformed(evt);
            }
        });

        lbLogged.setText("Sesion abierta como:");

        lbTitulo.setText("Completar datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbLogged)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(lbTitulo)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lbRegistro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tboxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbxEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbLogged, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lbRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tboxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Eventos para los placeholders de los textboxes
    private void tboxNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxNombreFocusGained
        if(tboxNombre.getText().equals("Ingrese su nombre completo")){
            tboxNombre.setText("");
            tboxNombre.setForeground(new Color(153,153,153));
        }  
    }//GEN-LAST:event_tboxNombreFocusGained

    private void tboxNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxNombreFocusLost
        if(tboxNombre.getText().equals("")){
            tboxNombre.setText("Ingrese su nombre completo");
            tboxNombre.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tboxNombreFocusLost

    private void tboxNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tboxNombreKeyTyped
        tboxNombre.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_tboxNombreKeyTyped

    private void tbxEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxEdadFocusGained
        if(tbxEdad.getText().equals("Ingrese su edad")){
            tbxEdad.setText("");
            tbxEdad.setForeground(new Color(153,153,153));
        }  
    }//GEN-LAST:event_tbxEdadFocusGained

    private void tbxEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxEdadFocusLost
        if(tbxEdad.getText().equals("")){
            tbxEdad.setText("Ingrese su edad");
            tbxEdad.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tbxEdadFocusLost

    private void tbxEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxEdadKeyTyped
        tbxEdad.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_tbxEdadKeyTyped

    //Evento del boton para subir el nombre y la edad del usuario
    private void btnCompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletarActionPerformed
        if (tbxEdad.getText()!="" && val.Edad(tbxEdad.getText())) {
            int edad = Integer.parseInt(tbxEdad.getText());
            usuarios.get(idUsuario).setNombre(tboxNombre.getText());
            usuarios.get(idUsuario).setEdad(edad);
            
            Bienvenido form = new Bienvenido(usuarios,idUsuario);
            form.setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Ingrese su nombre y su edad");
        }
    }//GEN-LAST:event_btnCompletarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Completar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Completar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Completar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Completar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Completar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompletar;
    private javax.swing.JLabel lbLogged;
    private javax.swing.JLabel lbRegistro;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField tboxNombre;
    private javax.swing.JTextField tbxEdad;
    // End of variables declaration//GEN-END:variables
}
