/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Edy
 */

public class Login extends javax.swing.JFrame {
    ArrayList<Usuario> usuarios;//lista de usuarios existentes

    /**
     * Creates new form Login
     */
    public Login() {
        this.usuarios = new ArrayList<>();
        initComponents();
    }
    
    //Para llamar al form y automaticamente agregarle la lista de usuarios
    public Login(ArrayList<Usuario> usuarios) {
        this.usuarios = usuarios;
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        tboxUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pfieldContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnIniciar.setText("Iniciar Sesion");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        tboxUsuario.setText("Ingrese su usuario");
        tboxUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tboxUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tboxUsuarioFocusLost(evt);
            }
        });
        tboxUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tboxUsuarioKeyTyped(evt);
            }
        });

        jLabel1.setText("¿No tienes cuenta?, registrate aqui:");

        jLabel3.setText("Login de usuario");

        pfieldContraseña.setText("**************");
        pfieldContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfieldContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfieldContraseñaFocusLost(evt);
            }
        });
        pfieldContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfieldContraseñaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarse))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pfieldContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tboxUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(tboxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarse)
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Eventos para los placeholders de los textboxes
    private void tboxUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxUsuarioFocusGained
        if(tboxUsuario.getText().equals("Ingrese su usuario")){
            tboxUsuario.setText("");
            tboxUsuario.setForeground(new Color(153,153,153));
        }  
    }//GEN-LAST:event_tboxUsuarioFocusGained

    private void tboxUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxUsuarioFocusLost
        if(tboxUsuario.getText().equals("")){
            tboxUsuario.setText("Ingrese su usuario");
            tboxUsuario.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tboxUsuarioFocusLost

    private void pfieldContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfieldContraseñaFocusGained
        char[] pass = pfieldContraseña.getPassword();
        if(String.valueOf(pass).equals("**************")){
            pfieldContraseña.setText("");
            pfieldContraseña.setForeground(new Color(153,153,153));
        }  
    }//GEN-LAST:event_pfieldContraseñaFocusGained

    private void pfieldContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfieldContraseñaFocusLost
        char[] pass = pfieldContraseña.getPassword();
        if(String.valueOf(pass).equals("")){
            pfieldContraseña.setText("**************");
            pfieldContraseña.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pfieldContraseñaFocusLost

    private void pfieldContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfieldContraseñaKeyTyped
        pfieldContraseña.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pfieldContraseñaKeyTyped
    
    //Evento del boton para logearse
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        //variables para luego validar formato, y comprobar si existe el usuario
        int idUsuario;
        String usuario = tboxUsuario.getText();
        String contrasena = String.valueOf(pfieldContraseña.getPassword());
        
        Validaciones val = new Validaciones();
        
        //Checamos si usuario y contraseña son validos
        //Validacion del usuario
        if(!val.usuario(usuario)){
            JOptionPane.showMessageDialog(this, "El usuario tiene que empezar con una letra"
                    + "puede tener caracteres de a-z, A-Z, 0-9, incluyendo el _.");
        }
        //Validacion de la contraseña
        else if(!val.contrasena(contrasena)){
            JOptionPane.showMessageDialog(this, "La contraseña tiene que contar con al menos, "
                    + "una minuscula, una mayuscula, una letra, un caracter especial (@#$%^&+=), "
                    + "no debe de tener espacios y un largo de entre 8 y 30 caracteres.");
        }
        else
        {   
            //Vemos si el usuario no existe ya en la lista
            idUsuario = val.buscarUsuario(usuario, contrasena, usuarios);
            if(-1!=idUsuario)
            {
                //Si esta en la lista y es su primera vez lo manda a completar los datos
                if (usuarios.get(idUsuario).getNombre()==null) {
                    Completar form = new Completar(usuarios,idUsuario);
                    form.setVisible(true);
                    this.dispose();
                }
                else
                {
                    //Si ya completo sus datos lo envia a la ventana de bienvenida
                    Bienvenido form = new Bienvenido(usuarios,idUsuario);
                    form.setVisible(true);
                    this.dispose();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "La cuenta no existe o los datos no fueron correctos.");
            }
        }
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    //Evento para registrarse
    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        Registro form = new Registro(usuarios);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void tboxUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tboxUsuarioKeyTyped
        tboxUsuario.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_tboxUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pfieldContraseña;
    private javax.swing.JTextField tboxUsuario;
    // End of variables declaration//GEN-END:variables
}
