/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Edy
 */
public class Registro extends javax.swing.JFrame {
    ArrayList<Usuario> usuarios;//lista de usuarios existentes
    /**
     * Creates new form Registro
     */
    
    public Registro() {
        initComponents();
    }
    
    //Para llamar al form y automaticamente agregarle la lista de usuarios
    public Registro(ArrayList<Usuario> usuarios) {
        initComponents();
        this.usuarios = usuarios;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarse = new javax.swing.JButton();
        tboxUsuario = new javax.swing.JTextField();
        lbRegistro = new javax.swing.JLabel();
        btnRegistrarse1 = new javax.swing.JButton();
        pfieldContrasena1 = new javax.swing.JPasswordField();
        pfieldContrasena2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        tboxUsuario.setText("Ingrese su usuario");
        tboxUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tboxUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tboxUsuarioFocusLost(evt);
            }
        });
        tboxUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tboxUsuarioKeyTyped(evt);
            }
        });

        lbRegistro.setText("Registro");

        btnRegistrarse1.setText("Cancelar");
        btnRegistrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarse1ActionPerformed(evt);
            }
        });

        pfieldContrasena1.setText("**************");
        pfieldContrasena1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfieldContrasena1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfieldContrasena1FocusLost(evt);
            }
        });
        pfieldContrasena1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfieldContrasena1KeyTyped(evt);
            }
        });

        pfieldContrasena2.setText("**************");
        pfieldContrasena2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfieldContrasena2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfieldContrasena2FocusLost(evt);
            }
        });
        pfieldContrasena2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfieldContrasena2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tboxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRegistro)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnRegistrarse1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addComponent(pfieldContrasena1)
                    .addComponent(pfieldContrasena2))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tboxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfieldContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfieldContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarse1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Eventos para los placeholders de los textboxes
    private void pfieldContrasena1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfieldContrasena1FocusGained
        char[] pass = pfieldContrasena1.getPassword();
        if(String.valueOf(pass).equals("**************")){
            pfieldContrasena1.setText("");
            pfieldContrasena1.setCaretColor(Color.gray);
        }
    }//GEN-LAST:event_pfieldContrasena1FocusGained

    private void pfieldContrasena1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfieldContrasena1FocusLost
        char[] pass = pfieldContrasena1.getPassword();
        if(String.valueOf(pass).equals("")){
            pfieldContrasena1.setText("**************");
            pfieldContrasena1.setCaretColor(Color.gray);
        }
    }//GEN-LAST:event_pfieldContrasena1FocusLost

    private void pfieldContrasena2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfieldContrasena2FocusGained
        char[] pass = pfieldContrasena2.getPassword();
        if(String.valueOf(pass).equals("**************")){
            pfieldContrasena2.setText("");
            pfieldContrasena2.setCaretColor(Color.gray);
        }
    }//GEN-LAST:event_pfieldContrasena2FocusGained

    private void pfieldContrasena2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfieldContrasena2FocusLost
        char[] pass = pfieldContrasena2.getPassword();
        if(String.valueOf(pass).equals("")){
            pfieldContrasena2.setText("**************");
            pfieldContrasena2.setCaretColor(Color.gray);
        }
    }//GEN-LAST:event_pfieldContrasena2FocusLost

    private void pfieldContrasena1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfieldContrasena1KeyTyped
        pfieldContrasena2.setCaretColor(Color.BLACK);
    }//GEN-LAST:event_pfieldContrasena1KeyTyped

    private void pfieldContrasena2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfieldContrasena2KeyTyped
        tboxUsuario.setForeground(Color.BLACK);
    }//GEN-LAST:event_pfieldContrasena2KeyTyped

    //Evento del boton para registrarse
    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        //Sacamos el usuario y la contraseña de los texboxes
        String usuario = tboxUsuario.getText();
        String contrasena = String.valueOf(pfieldContrasena1.getPassword());
        
        //Construccion del la clase que tiene las validaciones
        Validaciones val = new Validaciones();
        //Checamos si usuario y contraseña son validos
        if(!val.usuario(usuario)){
            JOptionPane.showMessageDialog(this, "El usuario tiene que empezar con una letra"
                    + "puede tener caracteres de a-z, A-Z, 0-9, incluyendo el _.");
        }
        else if(!val.contrasena(contrasena)){
            JOptionPane.showMessageDialog(this, "La contraseña tiene que contar con al menos, "
                    + "una minuscula, una mayuscula, una letra, un caracter especial (@#$%^&+=), "
                    + "no debe de tener espacios y un largo de entre 8 y 30 caracteres.");
        }
        //Si son iguales ambos campos de las contraseñas
        else if (!Arrays.equals(pfieldContrasena1.getPassword(), pfieldContrasena2.getPassword())) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no se parecen.");
        }
        //Si no existe un usuario con el mismo nombre
        else if(val.existeUsuario(usuario, usuarios))
        {
            //Registramos la cuenta
            usuarios.add(new Usuario(usuario,contrasena));
            JOptionPane.showMessageDialog(this, "La cuenta fue registrada.");
            Login form = new Login(usuarios);
            form.setVisible(true);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(this, "Ese usuario ya existe.");
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    //Eventos para mostrar placeholders
    private void tboxUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxUsuarioFocusGained
        if(tboxUsuario.getText().equals("Ingrese su usuario")){
            tboxUsuario.setText("");
            tboxUsuario.setForeground(new Color(153,153,153));
        }  
    }//GEN-LAST:event_tboxUsuarioFocusGained

    private void tboxUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxUsuarioFocusLost
        if(tboxUsuario.getText().equals("")){
            tboxUsuario.setText("Ingrese su usuario");
            tboxUsuario.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tboxUsuarioFocusLost

    private void tboxUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tboxUsuarioKeyTyped
        tboxUsuario.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_tboxUsuarioKeyTyped

    //Evento para el boton que te devuelve al logun cuando cancelas el registro
    private void btnRegistrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarse1ActionPerformed
        Login form = new Login(usuarios);
            form.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnRegistrarse1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnRegistrarse1;
    private javax.swing.JLabel lbRegistro;
    private javax.swing.JPasswordField pfieldContrasena1;
    private javax.swing.JPasswordField pfieldContrasena2;
    private javax.swing.JTextField tboxUsuario;
    // End of variables declaration//GEN-END:variables
}
