/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Edy
 */

/*
Intrucciones
Dada una lista de números y un numero, usando métodos recursivos , imprimir las
combinaciones de números posibles que sumados sean igual al numero.
*/
public class Combinaciones extends javax.swing.JFrame {
    //Variables del form
    Combinar buscar = new Combinar();
    ArrayList<Integer> numeros = new ArrayList();
    
    /**
     * Creates new form
     */
    public Combinaciones() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNumero = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        tboxNumero = new javax.swing.JTextField();
        btnCorrer = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        tboxLista = new javax.swing.JTextField();
        lbLista = new javax.swing.JLabel();
        tboxObjetivo = new javax.swing.JTextField();
        lbObjetivo = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        tboxResultados = new javax.swing.JTextField();
        lbCombinaciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbNumero.setText("Numero:");

        btnAñadir.setText("Añadir a la lista");
        btnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAñadirMouseClicked(evt);
            }
        });

        tboxNumero.setForeground(new java.awt.Color(155, 155, 155));
        tboxNumero.setText("Ingrese un valor");
        tboxNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tboxNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tboxNumeroFocusLost(evt);
            }
        });
        tboxNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tboxNumeroKeyTyped(evt);
            }
        });

        btnCorrer.setText("Correr");
        btnCorrer.setActionCommand("btnCorrer");
        btnCorrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCorrerMouseClicked(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.setActionCommand("btnReiniciar");
        btnReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReiniciarMouseClicked(evt);
            }
        });

        tboxLista.setEditable(false);

        lbLista.setText("Lista de numeros:");

        tboxObjetivo.setForeground(new java.awt.Color(155, 155, 155));
        tboxObjetivo.setText("Ingrese un valor");
        tboxObjetivo.setToolTipText("");
        tboxObjetivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tboxObjetivoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tboxObjetivoFocusLost(evt);
            }
        });
        tboxObjetivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tboxObjetivoKeyTyped(evt);
            }
        });

        lbObjetivo.setText("Objetivo:");

        btnBorrar.setText("Borrar ultimo");
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });

        tboxResultados.setEditable(false);

        lbCombinaciones.setText("Combinaciones encontradas:");

        jLabel1.setText("Buscador de combinaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tboxResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tboxLista, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tboxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAñadir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbObjetivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tboxObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbLista)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCorrer, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReiniciar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbCombinaciones))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumero)
                    .addComponent(tboxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAñadir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLista)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tboxLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tboxObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbObjetivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnCorrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCombinaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tboxResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        lbNumero.getAccessibleContext().setAccessibleName("lbNumero");
        tboxNumero.getAccessibleContext().setAccessibleName("tboxNumero");
        tboxLista.getAccessibleContext().setAccessibleName("tboxLista");
        tboxObjetivo.getAccessibleContext().setAccessibleName("tboxObjetivo");
        lbObjetivo.getAccessibleContext().setAccessibleName("lbObjetivo");
        btnBorrar.getAccessibleContext().setAccessibleName("btnBorrar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo para validar que el texto ingresado es un numero
    public boolean ValidarNumero(String num) {
        
        if(num.length() >= 10  || Integer.parseInt(num) <= 0)
            return false;
        
        for (char c : num.toCharArray()) 
        { 
            if(!Character.isDigit(c))
                return false;
        }
        return true;
    }
    
    //Eventos para tener un placeholder en tboxNumero
    private void tboxNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxNumeroFocusGained
        if(tboxNumero.getText().equals("Ingrese un valor")){
            tboxNumero.setText("");
            tboxNumero.setForeground(new Color(153,153,153));
        }   
    }//GEN-LAST:event_tboxNumeroFocusGained

    private void tboxNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxNumeroFocusLost
        if(tboxNumero.getText().equals("")){
            tboxNumero.setText("Ingrese un valor");
            tboxNumero.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tboxNumeroFocusLost
	
	private void tboxNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tboxNumeroKeyTyped
        tboxNumero.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_tboxNumeroKeyTyped
	
    //Eventos para tener un placeholder en tboxObjetivo
	private void tboxObjetivoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxObjetivoFocusGained
        if(tboxObjetivo.getText().equals("Ingrese un valor")){
            tboxObjetivo.setText("");
            tboxObjetivo.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tboxObjetivoFocusGained

    private void tboxObjetivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tboxObjetivoFocusLost
        if(tboxObjetivo.getText().equals("")){
            tboxObjetivo.setText("Ingrese un valor");
            tboxObjetivo.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tboxObjetivoFocusLost

    private void tboxObjetivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tboxObjetivoKeyTyped
        tboxObjetivo.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_tboxObjetivoKeyTyped

    //Evento para añadir numeros a la lista de numeros
    private void btnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseClicked
        String num = tboxNumero.getText();
        
        if(ValidarNumero(num))
        {
            numeros.add(Integer.parseInt(num));
            tboxLista.setText(numeros.toString());
            tboxNumero.setText("Ingrese un valor");
        }
        else
            JOptionPane.showMessageDialog(this, "El numero a ingresar a la lista es muy largo o no contiene solo letras.");
    }//GEN-LAST:event_btnAñadirMouseClicked

    //Evento para sacar el ultimo numero de la lista
    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        if(numeros.size()>0)
        {
            numeros.remove(numeros.size()-1);
            tboxLista.setText(numeros.toString());
        }
    }//GEN-LAST:event_btnBorrarMouseClicked

    //Evento para correr el el metodo de busqueda convinaciones
    private void btnCorrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorrerMouseClicked
        
        ArrayList<ArrayList<Integer>> combinaciones;
        String num = tboxObjetivo.getText();
        String resultado = "";
        
        if(ValidarNumero(num))//Validamos el numero de la meta
        {
            //Buscamos convinaciones a travez del metodo BuscarCombinaciones
            //Al que le ingresamos la lista de numeros y la meta
             combinaciones = buscar.BuscarCombinaciones(numeros, Integer.parseInt(num));
             resultado+= combinaciones.toString();
             tboxResultados.setText(resultado);
        }
        else
            JOptionPane.showMessageDialog(this, "El numero objetivo es muy largo o no contiene solo letras.");
    }//GEN-LAST:event_btnCorrerMouseClicked

    //Para reiniciar todo
    private void btnReiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReiniciarMouseClicked
        numeros = new ArrayList();
        tboxLista.setText("");
        tboxNumero.setText("Ingrese un valor");
        tboxObjetivo.setText("Ingrese un valor");
        tboxResultados.setText("-");
    }//GEN-LAST:event_btnReiniciarMouseClicked

    @Override
    public void setLocation(int x, int y) {
        super.setLocation(x, y); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setLocation(Point p) {
        super.setLocation(p); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combinaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combinaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combinaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combinaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Combinaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCorrer;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCombinaciones;
    private javax.swing.JLabel lbLista;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbObjetivo;
    private javax.swing.JTextField tboxLista;
    private javax.swing.JTextField tboxNumero;
    private javax.swing.JTextField tboxObjetivo;
    private javax.swing.JTextField tboxResultados;
    // End of variables declaration//GEN-END:variables
}
